Lesson10
ditmarbrynza/qna pull request #19
Opened 2020-12-09 00:59 UTC by ditmarbrynza

Используя JSON, реализовать следующие истории:
 

 - Аутентифицированный пользователь может голосовать за понравившийся вопрос/ответ
 - Пользователь не может голосовать за свой вопрос/ответ
 - Пользователь может проголосовать "за" или "против" конкретного вопроса/ответа только один раз (нельзя голосовать 2 раза подряд "за" или "против")
 - Пользователь может отменить свое решение и после этого переголосовать.
 - У вопроса/ответа должен выводиться результирующий рейтинг (разница между голосами "за" и "против")

При реализации голосования запрещено использовать сторонние гемы для этого функционала

Рекомендации:
 - Посмотреть мастер-класс "Rails Concerns" (ссылка в дополнительных материалах к уроку) и реализовать возможность голосования через консерны.

2020-12-09 06:22 UTC, IvanShamatov requested changes
так, пока хватит

2020-12-09 06:22 UTC, IvanShamatov commented on app/models/vote.rb
> +    vote.destroy
какое интересное инженерное решение. Я не сразу врубился почему return_vote в конце у тебя делает destroy.

2020-12-09 06:22 UTC, IvanShamatov commented on app/models/vote.rb
> +  end
я понял, какую ты идею преследовал. Типа не использовать cancel_vote. Только у тебя логика неверная

```
        LIKED     DISLIKED
UP      1 => 0     1 => -1
DOWN   -1 => 1    -1 => 0
```

т.е. двойным лайком или двойным дислайком я привожу значение в 0.
Каким образом в голове пользователя может возникнуть идея, что если я нажму еще раз на стрелочку UP или DOWN, то у меня не плюсанется еще раз, а наоборот "отожмется кнопка"?
Я честно верю, что можно обойтись без этих методов в модели. А использовать что-то похожее на first_or_create как я показал выше в консерне.

2020-12-09 06:22 UTC, IvanShamatov commented on spec/features/answer/vote_spec.rb
> +        expect(page.find('.rating')).to have_content '0'
ага, ты ведь и правда именно "эффект отжатия" и реализовывал.
Как по мне, так это переключатель между -1, 0 и 1.

2020-12-09 23:15 UTC, ditmarbrynza commented on app/controllers/concerns/voted.rb
> +    Vote.votes[vote&.value.to_s]
> я не нашел такого метода у Vote класса. откуда он?

у модели есть enum vote: { '1': 'like', '-1': 'dislike' }

2020-12-09 23:15 UTC, ditmarbrynza commented on app/models/vote.rb
> +  end
> я понял, какую ты идею преследовал. Типа не использовать cancel_vote. Только у тебя логика неверная
> 
> ```
>         LIKED     DISLIKED
> UP      1 => 0     1 => -1
> DOWN   -1 => 1    -1 => 0
> ```
> 
> т.е. двойным лайком или двойным дислайком я привожу значение в 0.
> Каким образом в голове пользователя может возникнуть идея, что если я нажму еще раз на стрелочку UP или DOWN, то у меня не плюсанется еще раз, а наоборот "отожмется кнопка"?
> Я честно верю, что можно обойтись без этих методов в модели. А использовать что-то похожее на first_or_create как я показал выше в консерне.

обсудили в слэке

2020-12-09 23:15 UTC, ditmarbrynza commented on spec/features/answer/vote_spec.rb
> +        expect(page.find('.rating')).to have_content '0'
> ага, ты ведь и правда именно "эффект отжатия" и реализовывал.
> Как по мне, так это переключатель между -1, 0 и 1.

обсудили в слэке

2020-12-09 23:16 UTC, ditmarbrynza commented on app/models/vote.rb
> +    vote.destroy
> какое интересное инженерное решение. Я не сразу врубился почему return_vote в конце у тебя делает destroy.

спасибо

2020-12-09 23:27 UTC, ditmarbrynza commented on app/controllers/concerns/voted.rb
> +      if vote.nil? || vote.save
> вот это vote.nil? или vote.save нужно вытащить из respond_to блока.

А зачем? У меня там if else же. 2 раза чтоли respond_to писать при рендеринге json внутри if и при рендеригне внутри else?

2020-12-09 23:29 UTC, ditmarbrynza commented on app/controllers/concerns/voted.rb
> +    vote = Vote.up(current_user, votable)
исходя из обсуждения в слэке и моей реализации это более не актуально, как я понимаю)

2020-12-10 00:34 UTC, ditmarbrynza commented on app/views/answers/_answer.html.slim
> +            - if disliked?(current_user, answer)
> мы зайдем в обе ветки при рендеринге и в liked и disliked, и сделаем по факту два запроса в базу. А хотелось бы ХОТЯ БЫ один
один запрос сделал

> (я уж не говорю, что в целом можно сделать всего пару запросов на всю страницу)
как?

2020-12-10 00:34 UTC, ditmarbrynza commented on app/helpers/answer_helper.rb
> +    return unless vote.present?
> неправильная семаника.
> Если ты делаешь метод со знаком вопроса, то он должен возвращать булевое значение. Метод не должен возвращать nil

согласен

2020-12-10 00:35 UTC, ditmarbrynza commented on app/helpers/answer_helper.rb
> +  def how_voted(user, votable)
> я незнаю, может у меня чего с браузерным поиском, но я не нашел использование этого метода

он пригодился сейчас. задумывался для того, чтоб делать 1 запрос из бд. но потом я захотел быстрее сдать задание и забил и не удалил. но сейчас он пригодился

2020-12-10 08:47 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +    vote = Vote.up(current_user, votable)
ага, эта логика тут неприменима

2020-12-10 08:47 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +      if vote.nil? || vote.save
да, тут я протупил

2020-12-10 08:47 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +
```ruby
class Vote < ApplicationRecord
  enum value: { dislike: -1, like: 1 }
end

module Voted
  before_action :find_votable, :find_vote, only: %i[like dislike]
  respond_to :json, only: %i[like dislike]

  def render_votable(votable)
    render json: {
      votable_id: @votable.id,
      rating: @votable.rating,
      model: @votable.type,
      user_vote: @vote.value
    }
  end

  def like
    @vote ||= @votable.votes.create(user: current_user, value: :like)

    if @vote.like?
      @vote.destroy!
    else
      @vote.dislike!
    end
    render_votable(votable)
  end

  def dislike
    @vote ||= votable.votes.create(user: current_user, value: :dislike)

    if @vote.dislike?
      @vote.destroy!
    else
      @vote.dislike!
    end
    render_votable(votable)
  end

  def find_vote
    @vote = @votable.votes.find_by(user: current_user)
  end
end

```

Вот так мне видится этот модуль без дополнительных методов в модели
и если поубирать лишнее из экшенов контроллера (при сохранении твоей логики голосования).
Меньше кода -- всегда лучше

2020-12-10 09:21 UTC, ditmarbrynza commented on app/helpers/votes_helper.rb
> +    end
> Прости, я все еще не понимаю в чем смысл этого метода
> 
> ```
> рассмотрим значение голоса
> когда 1
>   то пусть 1
> когда -1
>   то пусть -1
> конец
> ```

Мне нужно понимать, как проголосовал юзер how_voted. Оттуда я возвращаю значение, во въюхе создаю инстанс переменную, затем закидываю ее в liked? и смотрю если лайк, то рендерю лайк черным цветом, что юзер на него нажал. Закидываю в disliked?, когда рендерю дизлайк, чтоб понять каким цветом рендерить эту икноку. По моему все логично здесь. Я не просто так константы ввел же, зачем читать когда 1 то пусть 1? Там константами ясно все написано, как по мне. Если like то возвращает liked, если дизлайк, что disliked

2020-12-11 23:50 UTC, ditmarbrynza commented on app/controllers/concerns/voted.rb
> +
откоментил в слэке

2020-12-12 07:34 UTC, IvanShamatov requested changes
Хорошо, задачи следующие:

1. сделай модуль Voted таким образом, чтобы не использовать классовых методов up и down в модели. По максимуму используй ассоциации и енум. Свою логику лайков при этом сохрани.
2. избавься от всего в VotesHelpers за счет правильного использования енума в модели. Этот хелпер не нужен целиком.

2020-12-14 06:33 UTC, IvanShamatov approved these changes

2020-12-14 08:20 UTC, merged